import type { Metadata } from "next";
import { AverageCalculator } from "@/components/calculators/AverageCalculator";
import { SEOContent } from "@/components/SEOContent";
import { Sigma } from "lucide-react";

export const metadata: Metadata = {
  title: "Average Calculator - Mean, Median & Sum | TopCalcBox",
  description: "Calculate the average (mean), median, sum, and count for any dataset. A free and fast online average calculator for students, teachers, and data analysis.",
};

export default function AverageCalculatorPage() {
  return (
    <div className="pb-8">
      {/* Schema Markup for SEO */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "Average Calculator",
            "operatingSystem": "Any",
            "applicationCategory": "EducationalApplication",
            "offers": {
              "@type": "Offer",
              "price": "0",
              "priceCurrency": "USD"
            }
          })
        }}
      />
    
      {/* Compact Premium Header */}
      <div className="flex flex-col md:flex-row items-center md:items-start md:justify-between bg-slate-900 rounded-[2rem] p-5 md:p-8 mb-6 mt-2 shadow-xl border border-slate-800 text-center md:text-left overflow-hidden relative">
        <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] bg-orange-500/20 rounded-full blur-[80px] pointer-events-none" />
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay pointer-events-none"></div>
        
        <div className="relative z-10 flex flex-col md:flex-row items-center md:items-center space-y-4 md:space-y-0 md:space-x-5 w-full">
          <div className="p-3.5 bg-white/10 rounded-2xl border border-white/10 shadow-sm backdrop-blur-md">
            <Sigma className="w-7 h-7 text-orange-400" />
          </div>
          <div className="flex-1">
            <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight mb-1">
              Average Calculator
            </h1>
            <p className="text-slate-300 text-sm md:text-base max-w-xl font-medium">
              Calculate the mean, median, sum, and count of your numbers instantly. Paste your dataset below.
            </p>
          </div>
        </div>
      </div>

      {/* Interactive Tool */}
      <div className="max-w-4xl mx-auto mb-10">
        <AverageCalculator />
      </div>

      {/* SEO Content Section */}
      <SEOContent>
        <h2>What is an Average Calculator?</h2>
        <p>
          An <strong>Average Calculator</strong> is a statistical tool designed to find the central tendency of a dataset. While the term "average" colloquially refers to the arithmetic mean, a comprehensive tool like the TopCalcBox Average Calculator also computes the median, the total sum of all values, and the count of numerical entries.
        </p>
        <p>
          This free online calculator takes the hassle out of manual data entry and complex arithmetic. Simply paste a list of numbers—separated by commas, spaces, or newlines—and the engine will instantly process the dataset to deliver highly accurate statistical results.
        </p>
        
        <h2>How to Use the Average Calculator</h2>
        <p>
          We've designed this tool to be as frictionless as possible. Here is how you can find your averages in seconds:
        </p>
        <ul>
          <li><strong>Step 1: Gather your data.</strong> Have your list of numbers ready.</li>
          <li><strong>Step 2: Enter the numbers.</strong> Paste or type the numbers into the large input field. You can separate them using commas (e.g., 10, 20, 30) or spaces (e.g., 10 20 30).</li>
          <li><strong>Step 3: View instant results.</strong> The calculator will immediately update the Mean, Median, Sum, and Count displays without requiring a page reload.</li>
        </ul>

        <h2>Understanding the Statistics</h2>
        <p>
          To make the most of this tool, it is helpful to understand what the resulting metrics represent:
        </p>
        <ul>
          <li><strong>Mean (Arithmetic Average):</strong> The sum of all numbers divided by the count of numbers. This is the most common measure of central tendency.</li>
          <li><strong>Median:</strong> The middle number when the dataset is sorted from smallest to largest. If there is an even number of data points, the median is the average of the two middle numbers. The median is highly useful for understanding datasets skewed by extreme outliers.</li>
          <li><strong>Sum:</strong> The total value generated by adding all numbers in the dataset together.</li>
          <li><strong>Count:</strong> The total number of valid numerical entries detected in your input.</li>
        </ul>

        <h2>Common Uses / Who Can Use It</h2>
        <ul>
          <li><strong>Students and Educators:</strong> Calculating average test scores, grades, or project marks for an entire class.</li>
          <li><strong>Data Analysts:</strong> Running quick statistical checks on small datasets without needing to boot up complex spreadsheet software.</li>
          <li><strong>Gamers and Athletes:</strong> Finding the average scores, kill/death ratios, or performance metrics over a series of matches.</li>
          <li><strong>Business Managers:</strong> Calculating average daily sales, weekly expenses, or average customer satisfaction ratings.</li>
        </ul>

      </SEOContent>
    </div>
  );
}
