import type { Metadata } from "next";
import { SEOContent } from "@/components/SEOContent";

export const metadata: Metadata = {
  title: "Terms and Conditions | TopCalcBox",
};

export default function Page() {
  return (
    <div className="pb-8">
      {/* Compact Premium Header */}
      <div className="bg-slate-900 rounded-[2rem] p-6 md:p-8 mb-8 mt-2 shadow-xl border border-slate-800 text-center overflow-hidden relative">
        <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] bg-orange-500/20 rounded-full blur-[80px] pointer-events-none" />
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay pointer-events-none"></div>
        <div className="relative z-10 flex flex-col items-center justify-center">
          <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight">
            Terms and Conditions
          </h1>
        </div>
      </div>
      <SEOContent>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using <strong>TopCalcBox</strong> (the "Website"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using this Website's particular services, you shall be subject to any posted guidelines or rules applicable to such services.
        </p>
        <h2>2. Informational Purposes Only</h2>
        <p>
          All calculations, tools, and content provided on TopCalcBox are strictly for informational and educational purposes. While we strive for accuracy, the results generated by our calculators should not be considered professional financial, legal, or medical advice. We do not guarantee the absolute accuracy or applicability of the results to your specific situation.
        </p>
        <h2>3. User Responsibilities</h2>
        <p>
          You agree to use TopCalcBox for lawful purposes only. You must not use our platform in any way that causes, or may cause, damage to the website or impairment of the availability or accessibility of the website.
        </p>
        <h2>4. Intellectual Property Rights</h2>
        <p>
          Unless otherwise stated, TopCalcBox and/or its licensors own the intellectual property rights for all material on the Website. All intellectual property rights are reserved. You may view and/or print pages from the Website for your own personal use subject to restrictions set in these terms and conditions.
        </p>
        <h2>5. Limitation of Liability</h2>
        <p>
          In no event shall TopCalcBox, nor any of its officers, directors, and employees, be held liable for anything arising out of or in any way connected with your use of this Website. We shall not be liable for any indirect, consequential, or special liability arising out of or in any way related to your use of our calculators.
        </p>

      </SEOContent>
    </div>
  );
}
