import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | TopCalcBox",
};

export default function Page() {
  return (
    <div className="pb-0 max-w-4xl mx-auto">
      <div className="bg-slate-900 rounded-[2rem] p-6 md:p-8 mb-6 mt-2 shadow-xl border border-slate-800 text-center overflow-hidden relative">
        <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] bg-orange-500/20 rounded-full blur-[80px] pointer-events-none" />
        <div className="relative z-10 flex flex-col items-center justify-center">
          <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight">Disclaimer</h1>
          <p className="text-slate-400 mt-2 text-sm">Last Updated: September 17, 2026</p>
        </div>
      </div>
      <div className="bg-white p-6 md:p-8 rounded-[2rem] border border-slate-200 shadow-sm text-slate-600 space-y-6 text-sm md:text-base leading-relaxed mb-4">
        <p>The information and calculator results provided on TopCalcBox are intended for general informational and educational purposes only.</p>
        <p>We try our best to keep our calculators accurate and useful, but we cannot guarantee that every result will always be completely accurate or suitable for every situation.</p>
        
        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">1. GENERAL INFORMATION</h2>
          <p>TopCalcBox provides online calculators for everyday calculations related to finance, math, education, dates, health, shopping, and other common needs. The results generated by our calculators should be used as general information and not as professional advice.</p>
        </div>

        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">2. FINANCIAL AND TAX CALCULATORS</h2>
          <p>Calculators such as EMI, SIP, GST, profit and loss, margin, discount, and other financial tools provide estimates based on the information entered by the user. Actual amounts may differ because of interest rates, taxes, fees, charges, rules, lender policies, or other factors. Please verify important financial or tax calculations with the relevant institution or a qualified professional before making a decision.</p>
        </div>

        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">3. HEALTH CALCULATORS</h2>
          <p>BMI, calorie, and other health-related calculators are provided for general informational purposes only. They are not intended to diagnose, treat, or prevent any medical condition. For health-related decisions, please consult a qualified healthcare professional.</p>
        </div>

        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">4. ACCURACY OF RESULTS</h2>
          <p>We make reasonable efforts to ensure that our calculators use appropriate formulas and provide accurate results. However, errors, rounding differences, changes in rules, or technical issues may sometimes affect the results. Always check important calculations before relying on them.</p>
        </div>

        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">5. USER INPUTS</h2>
          <p>The accuracy of a calculator result depends on the information entered by the user. You are responsible for checking your inputs and making sure that the information you enter is correct. TopCalcBox is not responsible for incorrect results caused by incorrect or incomplete information entered by the user.</p>
        </div>

        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">6. THIRD-PARTY INFORMATION AND SERVICES</h2>
          <p>Some information, advertisements, links, or services on TopCalcBox may come from third parties. We do not guarantee the accuracy, availability, or reliability of third-party websites or services. Please check the terms and policies of third-party services before using them.</p>
        </div>

        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">7. NO GUARANTEE</h2>
          <p>TopCalcBox does not guarantee that the website, calculators, or information will always be available, error-free, or suitable for every particular purpose. You use the website and its calculators at your own discretion and responsibility.</p>
        </div>

        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">8. CHANGES TO THIS DISCLAIMER</h2>
          <p>We may update this Disclaimer from time to time if our calculators, website, or services change. Any updates will be posted on this page with a new "Last Updated" date.</p>
        </div>

        <div>
          <h2 className="text-base md:text-lg font-bold text-slate-900 mb-1">9. CONTACT US</h2>
          <p>If you have any questions about this Disclaimer or any calculator on TopCalcBox, you can contact us at:</p>
          <p className="mt-1 font-bold text-orange-600">Email: help.rka@gmail.com</p>
        </div>
      </div>
    </div>
  );
}
